/*
 * Looker API 3.0 Reference
 * ### Authorization  The Looker API uses Looker **API3** credentials for authorization and access control. Looker admins can create API3 credentials on Looker's **Admin/Users** page. Pass API3 credentials to the **_/login** endpoint to obtain a temporary access_token. Include that access_token in the Authorization header of Looker API requests. For details, see [Looker API Authorization](https://looker.com/docs/r/api/authorization)  ### Client SDKs  The Looker API is a RESTful system that should be usable by any programming language capable of making HTTPS requests. Client SDKs for a variety of programming languages can be generated from the Looker API's Swagger JSON metadata to streamline use of the Looker API in your applications. A client SDK for Ruby is available as an example. For more information, see [Looker API Client SDKs](https://looker.com/docs/r/api/client_sdks)  ### Try It Out!  The 'api-docs' page served by the Looker instance includes 'Try It Out!' buttons for each API method. After logging in with API3 credentials, you can use the \"Try It Out!\" buttons to call the API directly from the documentation page to interactively explore API features and responses.  ### Versioning  Future releases of Looker will expand this API release-by-release to securely expose more and more of the core power of Looker to API client applications. API endpoints marked as \"beta\" may receive breaking changes without warning. Stable (non-beta) API endpoints should not receive breaking changes in future releases. For more information, see [Looker API Versioning](https://looker.com/docs/r/api/versioning) 
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * DashboardLayoutComponent
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-08T15:12:41.902+05:30")
public class DashboardLayoutComponent {
  @SerializedName("id")
  private String id = null;

  @SerializedName("dashboard_layout_id")
  private String dashboardLayoutId = null;

  @SerializedName("dashboard_element_id")
  private String dashboardElementId = null;

  @SerializedName("row")
  private Long row = null;

  @SerializedName("column")
  private Long column = null;

  @SerializedName("width")
  private Long width = null;

  @SerializedName("height")
  private Long height = null;

  @SerializedName("deleted")
  private Boolean deleted = null;

  @SerializedName("can")
  private Map<String, Boolean> can = null;

   /**
   * Unique Id
   * @return id
  **/
  @ApiModelProperty(value = "Unique Id")
  public String getId() {
    return id;
  }

   /**
   * Id of Dashboard Layout
   * @return dashboardLayoutId
  **/
  @ApiModelProperty(value = "Id of Dashboard Layout")
  public String getDashboardLayoutId() {
    return dashboardLayoutId;
  }

  public DashboardLayoutComponent dashboardElementId(String dashboardElementId) {
    this.dashboardElementId = dashboardElementId;
    return this;
  }

   /**
   * Id Of Dashboard Element
   * @return dashboardElementId
  **/
  @ApiModelProperty(value = "Id Of Dashboard Element")
  public String getDashboardElementId() {
    return dashboardElementId;
  }

  public void setDashboardElementId(String dashboardElementId) {
    this.dashboardElementId = dashboardElementId;
  }

  public DashboardLayoutComponent row(Long row) {
    this.row = row;
    return this;
  }

   /**
   * Row
   * @return row
  **/
  @ApiModelProperty(value = "Row")
  public Long getRow() {
    return row;
  }

  public void setRow(Long row) {
    this.row = row;
  }

  public DashboardLayoutComponent column(Long column) {
    this.column = column;
    return this;
  }

   /**
   * Column
   * @return column
  **/
  @ApiModelProperty(value = "Column")
  public Long getColumn() {
    return column;
  }

  public void setColumn(Long column) {
    this.column = column;
  }

  public DashboardLayoutComponent width(Long width) {
    this.width = width;
    return this;
  }

   /**
   * Width
   * @return width
  **/
  @ApiModelProperty(value = "Width")
  public Long getWidth() {
    return width;
  }

  public void setWidth(Long width) {
    this.width = width;
  }

  public DashboardLayoutComponent height(Long height) {
    this.height = height;
    return this;
  }

   /**
   * Height
   * @return height
  **/
  @ApiModelProperty(value = "Height")
  public Long getHeight() {
    return height;
  }

  public void setHeight(Long height) {
    this.height = height;
  }

   /**
   * Whether or not the dashboard layout component is deleted
   * @return deleted
  **/
  @ApiModelProperty(value = "Whether or not the dashboard layout component is deleted")
  public Boolean isDeleted() {
    return deleted;
  }

  public DashboardLayoutComponent can(Map<String, Boolean> can) {
    this.can = can;
    return this;
  }

  public DashboardLayoutComponent putCanItem(String key, Boolean canItem) {
    if (this.can == null) {
      this.can = new HashMap<String, Boolean>();
    }
    this.can.put(key, canItem);
    return this;
  }

   /**
   * Operations the current user is able to perform on this object
   * @return can
  **/
  @ApiModelProperty(value = "Operations the current user is able to perform on this object")
  public Map<String, Boolean> getCan() {
    return can;
  }

  public void setCan(Map<String, Boolean> can) {
    this.can = can;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DashboardLayoutComponent dashboardLayoutComponent = (DashboardLayoutComponent) o;
    return Objects.equals(this.id, dashboardLayoutComponent.id) &&
        Objects.equals(this.dashboardLayoutId, dashboardLayoutComponent.dashboardLayoutId) &&
        Objects.equals(this.dashboardElementId, dashboardLayoutComponent.dashboardElementId) &&
        Objects.equals(this.row, dashboardLayoutComponent.row) &&
        Objects.equals(this.column, dashboardLayoutComponent.column) &&
        Objects.equals(this.width, dashboardLayoutComponent.width) &&
        Objects.equals(this.height, dashboardLayoutComponent.height) &&
        Objects.equals(this.deleted, dashboardLayoutComponent.deleted) &&
        Objects.equals(this.can, dashboardLayoutComponent.can);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, dashboardLayoutId, dashboardElementId, row, column, width, height, deleted, can);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DashboardLayoutComponent {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    dashboardLayoutId: ").append(toIndentedString(dashboardLayoutId)).append("\n");
    sb.append("    dashboardElementId: ").append(toIndentedString(dashboardElementId)).append("\n");
    sb.append("    row: ").append(toIndentedString(row)).append("\n");
    sb.append("    column: ").append(toIndentedString(column)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    can: ").append(toIndentedString(can)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

