/*
 * Looker API 3.0 Reference
 * ### Authorization  The Looker API uses Looker **API3** credentials for authorization and access control. Looker admins can create API3 credentials on Looker's **Admin/Users** page. Pass API3 credentials to the **_/login** endpoint to obtain a temporary access_token. Include that access_token in the Authorization header of Looker API requests. For details, see [Looker API Authorization](https://looker.com/docs/r/api/authorization)  ### Client SDKs  The Looker API is a RESTful system that should be usable by any programming language capable of making HTTPS requests. Client SDKs for a variety of programming languages can be generated from the Looker API's Swagger JSON metadata to streamline use of the Looker API in your applications. A client SDK for Ruby is available as an example. For more information, see [Looker API Client SDKs](https://looker.com/docs/r/api/client_sdks)  ### Try It Out!  The 'api-docs' page served by the Looker instance includes 'Try It Out!' buttons for each API method. After logging in with API3 credentials, you can use the \"Try It Out!\" buttons to call the API directly from the documentation page to interactively explore API features and responses.  ### Versioning  Future releases of Looker will expand this API release-by-release to securely expose more and more of the core power of Looker to API client applications. API endpoints marked as \"beta\" may receive breaking changes without warning. Stable (non-beta) API endpoints should not receive breaking changes in future releases. For more information, see [Looker API Versioning](https://looker.com/docs/r/api/versioning) 
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IntegrationParam;
import io.swagger.client.model.IntegrationRequiredField;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Integration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-08T15:12:41.902+05:30")
public class Integration {
  @SerializedName("id")
  private String id = null;

  @SerializedName("integration_hub_id")
  private Long integrationHubId = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("params")
  private List<IntegrationParam> params = null;

  @SerializedName("supported_formats")
  private List<String> supportedFormats = null;

  @SerializedName("supported_action_types")
  private List<String> supportedActionTypes = null;

  @SerializedName("supported_formattings")
  private List<String> supportedFormattings = null;

  @SerializedName("supported_visualization_formattings")
  private List<String> supportedVisualizationFormattings = null;

  @SerializedName("supported_download_settings")
  private List<String> supportedDownloadSettings = null;

  @SerializedName("icon_url")
  private String iconUrl = null;

  @SerializedName("required_fields")
  private List<IntegrationRequiredField> requiredFields = null;

  @SerializedName("can")
  private Map<String, Boolean> can = null;

   /**
   * ID of the integration.
   * @return id
  **/
  @ApiModelProperty(value = "ID of the integration.")
  public String getId() {
    return id;
  }

   /**
   * ID of the integration hub.
   * @return integrationHubId
  **/
  @ApiModelProperty(value = "ID of the integration hub.")
  public Long getIntegrationHubId() {
    return integrationHubId;
  }

   /**
   * Label for the integration.
   * @return label
  **/
  @ApiModelProperty(value = "Label for the integration.")
  public String getLabel() {
    return label;
  }

   /**
   * Description of the integration.
   * @return description
  **/
  @ApiModelProperty(value = "Description of the integration.")
  public String getDescription() {
    return description;
  }

  public Integration enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Whether the integration is available to users.
   * @return enabled
  **/
  @ApiModelProperty(value = "Whether the integration is available to users.")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public Integration params(List<IntegrationParam> params) {
    this.params = params;
    return this;
  }

  public Integration addParamsItem(IntegrationParam paramsItem) {
    if (this.params == null) {
      this.params = new ArrayList<IntegrationParam>();
    }
    this.params.add(paramsItem);
    return this;
  }

   /**
   * Array of params for the integration.
   * @return params
  **/
  @ApiModelProperty(value = "Array of params for the integration.")
  public List<IntegrationParam> getParams() {
    return params;
  }

  public void setParams(List<IntegrationParam> params) {
    this.params = params;
  }

  public Integration supportedFormats(List<String> supportedFormats) {
    this.supportedFormats = supportedFormats;
    return this;
  }

  public Integration addSupportedFormatsItem(String supportedFormatsItem) {
    if (this.supportedFormats == null) {
      this.supportedFormats = new ArrayList<String>();
    }
    this.supportedFormats.add(supportedFormatsItem);
    return this;
  }

   /**
   * A list of data formats the integration supports. Valid values are: \&quot;txt\&quot;, \&quot;csv\&quot;, \&quot;inline_json\&quot;, \&quot;json\&quot;, \&quot;json_detail\&quot;, \&quot;xlsx\&quot;, \&quot;html\&quot;, \&quot;wysiwyg_pdf\&quot;, \&quot;assembled_pdf\&quot;, \&quot;wysiwyg_png\&quot;, \&quot;csv_zip\&quot;.
   * @return supportedFormats
  **/
  @ApiModelProperty(value = "A list of data formats the integration supports. Valid values are: \"txt\", \"csv\", \"inline_json\", \"json\", \"json_detail\", \"xlsx\", \"html\", \"wysiwyg_pdf\", \"assembled_pdf\", \"wysiwyg_png\", \"csv_zip\".")
  public List<String> getSupportedFormats() {
    return supportedFormats;
  }

  public void setSupportedFormats(List<String> supportedFormats) {
    this.supportedFormats = supportedFormats;
  }

  public Integration supportedActionTypes(List<String> supportedActionTypes) {
    this.supportedActionTypes = supportedActionTypes;
    return this;
  }

  public Integration addSupportedActionTypesItem(String supportedActionTypesItem) {
    if (this.supportedActionTypes == null) {
      this.supportedActionTypes = new ArrayList<String>();
    }
    this.supportedActionTypes.add(supportedActionTypesItem);
    return this;
  }

   /**
   * A list of action types the integration supports. Valid values are: \&quot;cell\&quot;, \&quot;query\&quot;, \&quot;dashboard\&quot;.
   * @return supportedActionTypes
  **/
  @ApiModelProperty(value = "A list of action types the integration supports. Valid values are: \"cell\", \"query\", \"dashboard\".")
  public List<String> getSupportedActionTypes() {
    return supportedActionTypes;
  }

  public void setSupportedActionTypes(List<String> supportedActionTypes) {
    this.supportedActionTypes = supportedActionTypes;
  }

  public Integration supportedFormattings(List<String> supportedFormattings) {
    this.supportedFormattings = supportedFormattings;
    return this;
  }

  public Integration addSupportedFormattingsItem(String supportedFormattingsItem) {
    if (this.supportedFormattings == null) {
      this.supportedFormattings = new ArrayList<String>();
    }
    this.supportedFormattings.add(supportedFormattingsItem);
    return this;
  }

   /**
   * A list of formatting options the integration supports. Valid values are: \&quot;formatted\&quot;, \&quot;unformatted\&quot;.
   * @return supportedFormattings
  **/
  @ApiModelProperty(value = "A list of formatting options the integration supports. Valid values are: \"formatted\", \"unformatted\".")
  public List<String> getSupportedFormattings() {
    return supportedFormattings;
  }

  public void setSupportedFormattings(List<String> supportedFormattings) {
    this.supportedFormattings = supportedFormattings;
  }

  public Integration supportedVisualizationFormattings(List<String> supportedVisualizationFormattings) {
    this.supportedVisualizationFormattings = supportedVisualizationFormattings;
    return this;
  }

  public Integration addSupportedVisualizationFormattingsItem(String supportedVisualizationFormattingsItem) {
    if (this.supportedVisualizationFormattings == null) {
      this.supportedVisualizationFormattings = new ArrayList<String>();
    }
    this.supportedVisualizationFormattings.add(supportedVisualizationFormattingsItem);
    return this;
  }

   /**
   * A list of visualization formatting options the integration supports. Valid values are: \&quot;apply\&quot;, \&quot;noapply\&quot;.
   * @return supportedVisualizationFormattings
  **/
  @ApiModelProperty(value = "A list of visualization formatting options the integration supports. Valid values are: \"apply\", \"noapply\".")
  public List<String> getSupportedVisualizationFormattings() {
    return supportedVisualizationFormattings;
  }

  public void setSupportedVisualizationFormattings(List<String> supportedVisualizationFormattings) {
    this.supportedVisualizationFormattings = supportedVisualizationFormattings;
  }

  public Integration supportedDownloadSettings(List<String> supportedDownloadSettings) {
    this.supportedDownloadSettings = supportedDownloadSettings;
    return this;
  }

  public Integration addSupportedDownloadSettingsItem(String supportedDownloadSettingsItem) {
    if (this.supportedDownloadSettings == null) {
      this.supportedDownloadSettings = new ArrayList<String>();
    }
    this.supportedDownloadSettings.add(supportedDownloadSettingsItem);
    return this;
  }

   /**
   * A list of streaming options the integration supports. Valid values are: \&quot;push\&quot;, \&quot;url\&quot;.
   * @return supportedDownloadSettings
  **/
  @ApiModelProperty(value = "A list of streaming options the integration supports. Valid values are: \"push\", \"url\".")
  public List<String> getSupportedDownloadSettings() {
    return supportedDownloadSettings;
  }

  public void setSupportedDownloadSettings(List<String> supportedDownloadSettings) {
    this.supportedDownloadSettings = supportedDownloadSettings;
  }

   /**
   * URL to an icon for the integration.
   * @return iconUrl
  **/
  @ApiModelProperty(value = "URL to an icon for the integration.")
  public String getIconUrl() {
    return iconUrl;
  }

  public Integration requiredFields(List<IntegrationRequiredField> requiredFields) {
    this.requiredFields = requiredFields;
    return this;
  }

  public Integration addRequiredFieldsItem(IntegrationRequiredField requiredFieldsItem) {
    if (this.requiredFields == null) {
      this.requiredFields = new ArrayList<IntegrationRequiredField>();
    }
    this.requiredFields.add(requiredFieldsItem);
    return this;
  }

   /**
   * A list of descriptions of required fields that this integration is compatible with. If there are multiple entries in this list, the integration requires more than one field.
   * @return requiredFields
  **/
  @ApiModelProperty(value = "A list of descriptions of required fields that this integration is compatible with. If there are multiple entries in this list, the integration requires more than one field.")
  public List<IntegrationRequiredField> getRequiredFields() {
    return requiredFields;
  }

  public void setRequiredFields(List<IntegrationRequiredField> requiredFields) {
    this.requiredFields = requiredFields;
  }

  public Integration can(Map<String, Boolean> can) {
    this.can = can;
    return this;
  }

  public Integration putCanItem(String key, Boolean canItem) {
    if (this.can == null) {
      this.can = new HashMap<String, Boolean>();
    }
    this.can.put(key, canItem);
    return this;
  }

   /**
   * Operations the current user is able to perform on this object
   * @return can
  **/
  @ApiModelProperty(value = "Operations the current user is able to perform on this object")
  public Map<String, Boolean> getCan() {
    return can;
  }

  public void setCan(Map<String, Boolean> can) {
    this.can = can;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Integration integration = (Integration) o;
    return Objects.equals(this.id, integration.id) &&
        Objects.equals(this.integrationHubId, integration.integrationHubId) &&
        Objects.equals(this.label, integration.label) &&
        Objects.equals(this.description, integration.description) &&
        Objects.equals(this.enabled, integration.enabled) &&
        Objects.equals(this.params, integration.params) &&
        Objects.equals(this.supportedFormats, integration.supportedFormats) &&
        Objects.equals(this.supportedActionTypes, integration.supportedActionTypes) &&
        Objects.equals(this.supportedFormattings, integration.supportedFormattings) &&
        Objects.equals(this.supportedVisualizationFormattings, integration.supportedVisualizationFormattings) &&
        Objects.equals(this.supportedDownloadSettings, integration.supportedDownloadSettings) &&
        Objects.equals(this.iconUrl, integration.iconUrl) &&
        Objects.equals(this.requiredFields, integration.requiredFields) &&
        Objects.equals(this.can, integration.can);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, integrationHubId, label, description, enabled, params, supportedFormats, supportedActionTypes, supportedFormattings, supportedVisualizationFormattings, supportedDownloadSettings, iconUrl, requiredFields, can);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Integration {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    integrationHubId: ").append(toIndentedString(integrationHubId)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    supportedFormats: ").append(toIndentedString(supportedFormats)).append("\n");
    sb.append("    supportedActionTypes: ").append(toIndentedString(supportedActionTypes)).append("\n");
    sb.append("    supportedFormattings: ").append(toIndentedString(supportedFormattings)).append("\n");
    sb.append("    supportedVisualizationFormattings: ").append(toIndentedString(supportedVisualizationFormattings)).append("\n");
    sb.append("    supportedDownloadSettings: ").append(toIndentedString(supportedDownloadSettings)).append("\n");
    sb.append("    iconUrl: ").append(toIndentedString(iconUrl)).append("\n");
    sb.append("    requiredFields: ").append(toIndentedString(requiredFields)).append("\n");
    sb.append("    can: ").append(toIndentedString(can)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

