/*
 * Looker API 3.0 Reference
 * ### Authorization  The Looker API uses Looker **API3** credentials for authorization and access control. Looker admins can create API3 credentials on Looker's **Admin/Users** page. Pass API3 credentials to the **_/login** endpoint to obtain a temporary access_token. Include that access_token in the Authorization header of Looker API requests. For details, see [Looker API Authorization](https://looker.com/docs/r/api/authorization)  ### Client SDKs  The Looker API is a RESTful system that should be usable by any programming language capable of making HTTPS requests. Client SDKs for a variety of programming languages can be generated from the Looker API's Swagger JSON metadata to streamline use of the Looker API in your applications. A client SDK for Ruby is available as an example. For more information, see [Looker API Client SDKs](https://looker.com/docs/r/api/client_sdks)  ### Try It Out!  The 'api-docs' page served by the Looker instance includes 'Try It Out!' buttons for each API method. After logging in with API3 credentials, you can use the \"Try It Out!\" buttons to call the API directly from the documentation page to interactively explore API features and responses.  ### Versioning  Future releases of Looker will expand this API release-by-release to securely expose more and more of the core power of Looker to API client applications. API endpoints marked as \"beta\" may receive breaking changes without warning. Stable (non-beta) API endpoints should not receive breaking changes in future releases. For more information, see [Looker API Versioning](https://looker.com/docs/r/api/versioning) 
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ModelsNotValidated;
import io.swagger.client.model.ProjectError;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ProjectValidationCache
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-08T15:12:41.902+05:30")
public class ProjectValidationCache {
  @SerializedName("errors")
  private List<ProjectError> errors = null;

  @SerializedName("project_digest")
  private String projectDigest = null;

  @SerializedName("models_not_validated")
  private List<ModelsNotValidated> modelsNotValidated = null;

  @SerializedName("stale")
  private Boolean stale = null;

  public ProjectValidationCache errors(List<ProjectError> errors) {
    this.errors = errors;
    return this;
  }

  public ProjectValidationCache addErrorsItem(ProjectError errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<ProjectError>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * A list of project errors
   * @return errors
  **/
  @ApiModelProperty(value = "A list of project errors")
  public List<ProjectError> getErrors() {
    return errors;
  }

  public void setErrors(List<ProjectError> errors) {
    this.errors = errors;
  }

   /**
   * A hash value computed from the project&#39;s current state
   * @return projectDigest
  **/
  @ApiModelProperty(value = "A hash value computed from the project's current state")
  public String getProjectDigest() {
    return projectDigest;
  }

  public ProjectValidationCache modelsNotValidated(List<ModelsNotValidated> modelsNotValidated) {
    this.modelsNotValidated = modelsNotValidated;
    return this;
  }

  public ProjectValidationCache addModelsNotValidatedItem(ModelsNotValidated modelsNotValidatedItem) {
    if (this.modelsNotValidated == null) {
      this.modelsNotValidated = new ArrayList<ModelsNotValidated>();
    }
    this.modelsNotValidated.add(modelsNotValidatedItem);
    return this;
  }

   /**
   * A list of models which were not fully validated
   * @return modelsNotValidated
  **/
  @ApiModelProperty(value = "A list of models which were not fully validated")
  public List<ModelsNotValidated> getModelsNotValidated() {
    return modelsNotValidated;
  }

  public void setModelsNotValidated(List<ModelsNotValidated> modelsNotValidated) {
    this.modelsNotValidated = modelsNotValidated;
  }

   /**
   * If true, the cached project validation results are no longer accurate because the project has changed since the cached results were calculated
   * @return stale
  **/
  @ApiModelProperty(value = "If true, the cached project validation results are no longer accurate because the project has changed since the cached results were calculated")
  public Boolean isStale() {
    return stale;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectValidationCache projectValidationCache = (ProjectValidationCache) o;
    return Objects.equals(this.errors, projectValidationCache.errors) &&
        Objects.equals(this.projectDigest, projectValidationCache.projectDigest) &&
        Objects.equals(this.modelsNotValidated, projectValidationCache.modelsNotValidated) &&
        Objects.equals(this.stale, projectValidationCache.stale);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errors, projectDigest, modelsNotValidated, stale);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectValidationCache {\n");
    
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    projectDigest: ").append(toIndentedString(projectDigest)).append("\n");
    sb.append("    modelsNotValidated: ").append(toIndentedString(modelsNotValidated)).append("\n");
    sb.append("    stale: ").append(toIndentedString(stale)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

